config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "questions#index"

  get 'search_results/index'
  get '/users/add_email', to: 'users#add_email'
  post '/users/finish_signup', to: 'users#finish_signup'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :subscriptions, only: [:create, :destroy]
    resources :comments, shallow: true, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      resources :comments, only: :create
      patch :set_best, on: :member
    end
  end

  resources :attachments, only: :destroy
  resources :users, except: [:new, :edit]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  validates :body, :user_id, :commentable_id, :commentable_type, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable, only: :create
  before_action :load_comment, only: :destroy

  authorize_resource

  def create
    respond_with(@comment = @commentable.comments.create(comment_params.merge(user: current_user)))
  end

  def destroy
    respond_with(@comment.destroy)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        @commentable = $1.classify.constantize.find(value)
      end
    end
  end

  def load_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.comment id="comment-#{comment.id}"
  - cache [ 'comment', comment ] do
    .col-md-8
      = comment.body
      p
        ||
        i.glyphicon.glyphicon-user
        = link_to comment.user.name, comment.user
        ||
        i.glyphicon.glyphicon-calendar
        = comment.created_at.strftime("%d.%m.%y")
        ||
  .col-md-1
      - if can? :modify, comment
        = link_to '', comment_path(comment),remote: true, method: :delete, class: 'glyphicon glyphicon-trash'

app/views/comments/_form.html.slim
= simple_form_for [commentable, comment], remote: true do |f|
  .comment-errors
  = f.input :body, placeholder: "Оставте ваш комментарий"
  = button_tag "Комментировать", type: 'submit', class: "btn btn-primary", title: "Оставить комментарий"

app/views/comments/create.js.erb
<% if @comment.commentable_type == "Question"%>
  <% if @comment.errors.present? %>
    <% @comment.errors.full_messages.each do |message| %>
      $(".question .comment-errors").addClass('alert alert-danger').html('<%= j message %>');
    <% end %>
  <% else %>
    $('.comments-list').append('<%= j render @comment %>');
    $('.question .comment-errors').hide();
    $('.question #comment_body').val('');
  <% end %>
<% else %>
  <% if @comment.errors.present? %>
    <% @comment.errors.full_messages.each do |message| %>
      $('<%= "#answer-#{@comment.commentable_id}" %> .comment-errors').addClass('alert alert-danger').html('<%= j message %>');
    <% end %>
  <% else %>
    $('<%= "#answer-comments-list-#{@comment.commentable_id}" %>').append('<%= j render @comment %>');
    $('<%= "#answer-#{@comment.commentable_id}" %> .comment-errors').hide();
    $('.answers #comment_body').val('');
  <% end %>
<% end %>

app/views/comments/destroy.js.erb
$('<%= "#comment-#{@comment.id}" %>').remove();