config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "questions#index"

  get 'search_results/index'
  get '/users/add_email', to: 'users#add_email'
  post '/users/finish_signup', to: 'users#finish_signup'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :subscriptions, only: [:create, :destroy]
    resources :comments, shallow: true, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      resources :comments, only: :create
      patch :set_best, on: :member
    end
  end

  resources :attachments, only: :destroy
  resources :users, except: [:new, :edit]
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, :question_id, :user_id, presence: true

  default_scope -> { order(best: :desc).order(created_at: :desc) }

  after_commit :send_answer_notification

  def set_best
    ActiveRecord::Base.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  private

  def send_answer_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:update, :destroy, :set_best]
  before_action :find_question, only: :create
  before_action :set_question, only: [:update, :set_best]

  include Voted

  authorize_resource

  def create
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_user)))
  end

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def destroy
    respond_with(@answer.destroy)
  end

  def set_best
    @answer.set_best
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_question
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit( :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .col-xs-12.answer id="answer-#{answer.id}"
    .col-xs-12
      .col-xs-9.col-md-8
        - cache [ 'answer', answer ] do
          = answer.body
      .col-xs-3.col-md-4
        - if answer.best?
          span class="glyphicon glyphicon-ok-circle" Лучший ответ
        - if (can? :set_best, answer) && !answer.best?
          = link_to '', set_best_answer_path(answer) , method: :patch, remote: true, class: "best-answer-link glyphicon glyphicon-ok", title: "Отметить как лучший"

    .col-xs-12
      = render 'shared/vote', object: answer, up: vote_up_answer_path(answer),
        down: vote_down_answer_path(answer), reset: vote_reset_answer_path(answer)

    .col-xs-12.manage-links.text-center
      p
      ||
      = link_to answer.user.name, answer.user, class: 'glyphicon glyphicon-user'
      - cache [ 'answer-info', answer ] do
        ||
        = answer.created_at.strftime("%d.%m.%y")
        ||
        = link_to "", "", class: 'answer-comments-link glyphicon glyphicon-comment', data: { answer_id: answer.id }, id: "answer-comments-link-#{answer.id}"
        ||
        = link_to "", "", class: "answer-attachments-link glyphicon glyphicon-file", data: { answer_id: answer.id }, id: "answer-attachments-link-#{answer.id}"
      - if can? :modify, answer
        ||
        = link_to '', answer_path(answer), remote: true, method: :delete, class: 'glyphicon glyphicon-trash', id: "delete-answer-link-#{answer.id}"
        ||
        = link_to '', '', class: 'edit-answer-link glyphicon glyphicon-pencil', data: { answer_id: answer.id }, id: "edit-answer-link-#{answer.id}"
      ||

    .col-xs-12
      .edit-answer id="edit-form-#{answer.id}"
        = simple_form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}"} do |f|
          .answer-edit-errors
          = f.input :body, label: "Ответ", as: :text
          = f.submit 'Сохранить', class: "btn btn-primary"

    .col-xs-12
      div class="attachments"  id="answer-attachments-#{answer.id}"
        = link_to "Закрыть", "", class: "close-attachments-link"
        = render 'shared/attachments', object: answer
        - if signed_in? && current_user.author_of?(answer)
          = form_for answer, html: { class: "add-file-answer", id: "add-file-answer-form-#{answer.id}"}, remote: true do |f|
            = render 'attachments/form', object: answer.attachments.build, f: f

    .col-xs-12
      div class="comments answer-comments" id="answer-comments-#{answer.id}"
        = link_to "Закрыть", "", class: "close-comments-link"
        div id="answer-comments-list-#{answer.id}"
          - if answer.comments.present?
              p Комментарии:
              = render answer.comments
        - if can? :create, Comment
          = render 'comments/form', comment: answer.comments.new, commentable: answer

app/views/answers/_form.html.slim
.col-xs-12.col-sm-offset-2.col-sm-8.col-md-offset-3.col-md-6
  hr
  = simple_form_for [@question, @answer], remote: true do |f|
    = f.input :body, label: 'Ваш ответ'
    .answer-errors
    br
    = f.fields_for :attachments, @answer.attachments.build do |a|
      = render 'attachments/attachment_fields', f: a
      .links
        = link_to_add_association "Добавить", f, :attachments, partial: 'attachments/attachment_fields', title: "Добавить еще один файл"
    = f.submit "Ответить", class: "btn btn-primary"

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').addClass('alert alert-danger').html('<%= j message %>');
    <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('.new_answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('<%= "#answer-#{@answer.id}" %>').remove();

app/views/answers/set_best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-edit-errors').addClass('alert alert-danger').html('<%= j message %>');
    <% end %>
<% else %>
    $('<%= "#answer-#{@answer.id}" %>').replaceWith('<%= j render @answer %>');
    $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
    });
<% end %>