config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "questions#index"

  get 'search_results/index'
  get '/users/add_email', to: 'users#add_email'
  post '/users/finish_signup', to: 'users#finish_signup'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :subscriptions, only: [:create, :destroy]
    resources :comments, shallow: true, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      resources :comments, only: :create
      patch :set_best, on: :member
    end
  end

  resources :attachments, only: :destroy
  resources :users, except: [:new, :edit]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question, touch: true

  validates :user_id, :question_id, presence: true
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question
  before_action :load_subscription, only: :destroy

  authorize_resource

  def create
    respond_with(@subscription = @question.subscriptions.create(user: current_user)) unless current_user.subscribed?(@question)
  end

  def destroy
    respond_with(@subscription.destroy)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.slim
.subscription
  - if signed_in?
    - unless current_user.subscribed?(@question)
      = link_to '', question_subscriptions_path(@question), method: :post, remote: true, class: 'subscribe-link glyphicon glyphicon-star-empty', title: "Добавить в избранное. На вашу почту будут приходить оповещения о появлении нового ответа."
    - if can? :destroy, @subscription
      = link_to '',  question_subscription_path(@question, @subscription), method: :delete, remote: true, class: 'unsubscribe-link glyphicon glyphicon-star', title: "Вопрос добавлен в избранное. Кликните для отмены."

app/views/subscriptions/create.js.erb
$('.subscribe-link').replaceWith("<%= j render 'subscription' %>");

app/views/subscriptions/destroy.js.erb
$('.unsubscribe-link').replaceWith("<%= j render 'subscription' %>");
$('.subscribed').remove();