config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: "questions#index"

  get 'search_results/index'
  get '/users/add_email', to: 'users#add_email'
  post '/users/finish_signup', to: 'users#finish_signup'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_reset
    end
  end

  resources :questions, concerns: :votable do
    resources :subscriptions, only: [:create, :destroy]
    resources :comments, shallow: true, only: [:create, :destroy]
    resources :answers, shallow: true, concerns: :votable do
      resources :comments, only: :create
      patch :set_best, on: :member
    end
  end

  resources :attachments, only: :destroy
  resources :users, except: [:new, :edit]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can :create, [Question, Answer, Comment]

    alias_action :update, :destroy, to: :modify
    can :modify, [Question, Answer, Comment], user: user

    can :destroy, Attachment, attachable: { user_id: user.id }

    can :set_best, Answer, question: { user_id: user.id }

    can :vote_reset, [Question, Answer] do |item|
      user.voted?(item)
    end

    alias_action :vote_up, :vote_down, to: :vote
    can :vote, [Question, Answer] do |item|
      !user.voted?(item)
    end

    cannot :vote, [Question, Answer], user: user

    can :me, User, id: user.id

    can :subscribe, Question do |question|
      !user.subscribed?(question)
    end
    can :unsubscribe, Question

    can :create, Subscription
    can :destroy, Subscription do |subscription|
      user.subscribed?(subscription.question)
    end

    can :update, User, id: user.id
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Attachable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body, :question_id, :user_id, presence: true

  default_scope -> { order(best: :desc).order(created_at: :desc) }

  after_commit :send_answer_notification

  def set_best
    ActiveRecord::Base.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end

  private

  def send_answer_notification
    AnswerNotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true, touch: true

  validates :file, presence: true

  mount_uploader :file, FileUploader
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  validates :body, :user_id, :commentable_id, :commentable_type, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  paginates_per 10

  include Attachable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  belongs_to :user

  validates :title, :body, :user_id, presence: true

  after_create :subscribe_owner

  private

  def subscribe_owner
    Subscription.create(question: self, user: self.user)
  end
end

app/models/search.rb
class Search
  SUBJECTS = %w(question answer comment user)

  def self.make_search(query, subject)
    if query.blank?
      return nil
    else
      if subject == 'all'
        ThinkingSphinx.search Riddle::Query.escape(query)
      elsif SUBJECTS.include? subject
        ThinkingSphinx.search Riddle::Query.escape(query), classes: [subject.classify.constantize]
      else
        nil
      end
    end
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question, touch: true

  validates :user_id, :question_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  paginates_per 10

  has_many :answers
  has_many :questions
  has_many :votes
  has_many :comments
  has_many :authorizations
  has_many :subscriptions, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :twitter]

  def author_of?(item)
    item.user_id == self.id
  end

  def voted?(obj)
    return obj.votes.find_by(user_id: self.id).present?
  end

  def self.find_for_oauth(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization
    if auth.info && auth.info[:email]
      email = auth.info[:email]
      user = User.find_by(email: email)
      if user
        user.create_authorization(auth)
      else
        password = Devise.friendly_token[0, 20]
        user = User.create(email: email, password: password, password_confirmation: password)
        user.create_authorization(auth)
      end
      return user
    else
      return nil
    end
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid.to_s)
  end

  def subscribed?(question)
    question.subscriptions.where(user: self).exists?
  end

  def self.send_daily_digest
    find_each.each do |user|
      DailyMailer.digest(user).deliver_later
     end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :votable, polymorphic: true, touch: true
  belongs_to :user

  validates :value, :votable_id, :votable_type, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :update
  before_action :load_user, except: [:index, :add_email, :finish_signup]
  before_action :set_auth_and_password, only: [:add_email, :finish_signup]

  skip_authorization_check

  def index
    respond_with(@users = User.all.page(params[:page]))
  end

  def show
    respond_with(@user)
  end

  def update
    authorize! :update, @user
    @user.update(user_params)
    respond_with(@user)
  end

  def add_email
    respond_with(@user = User.new)
  end

  def finish_signup
    if existing_user
      redirect_to root_path, notice: "Аккаунт успешно привязан к вашей учетной записи. Теперь вы можете входить в систему с помощью #{@provider.capitalize}."
    else
      @user = User.new(
        password: @password, password_confirmation: @password,
        email: user_params[:email]
      )
      if @user.save
        create_authorization_and_sign_in
        redirect_to root_path
      else
        render :add_email
      end
    end
  end

 private

  def set_auth_and_password
    @provider = session["devise.oauth_data"]['provider']
    @uid = session["devise.oauth_data"]['uid']
    @password = Devise.friendly_token[0, 20]
  end

  def existing_user
    if @user = User.find_by(email: user_params[:email])
      create_authorization_and_sign_in
      return true
    end
  end

  def create_authorization_and_sign_in
    @user.authorizations.create(provider: @provider, uid: @uid)
    sign_in(@user, :bypass => true)
  end

  def load_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :email, :name, :location, :description, :avatar, :remove_avatar
    )
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_results_helper.rb
module SearchResultsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
.container.text-center
  .row
    .col-lg-12
      ul.nav.navbar-inverse.navbar-fixed-bottom.nav-pills.nav-justified
        .col-md-6
          li
            a href="https://github.com/salta0/qna"  GitHub
        .col-md-6
          li svetlana.altukhova.asb@gmail.com

app/views/layouts/_header.html.slim
nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"
  .container
    div class="navbar-header"
      button  type="button" class="navbar-toggle" data-toggle="collapse" data-target="#responsive-menu"
        span class="icon-bar"
        span class="icon-bar"
        span class="icon-bar"
    div class="collapse navbar-collapse" id="responsive-menu"
      ul class="nav navbar-nav navbar-left"
        li id="logo" = link_to "QnA", root_path
        - if signed_in?
          li = link_to "Задать вопрос", new_question_path
          li = link_to "Мой профиль", user_path(current_user)
          li = link_to "Выйти", destroy_user_session_path, method: "delete"
        - else
          li = link_to "Аутентифицироваться", new_user_session_path
        li = link_to "Пользователи", users_path
      = render 'search_results/form'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="IE=edge" http-equiv="X-UA-Compatible"
    meta content="width=device-width, initial-scale=1" name="viewport"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = Gon::Base.render_data
    = csrf_meta_tags
  body
    .header
        = render 'layouts/header'
    .container.main-content
      .row
        .hidden-xs.page-header.text-center
          h1
            ' QnA
            small Сервис вопросов и ответов
      .row
        - if notice
          .alert.alert-info
            = notice
        - if alert
          .alert.alert-danger
            = alert
      = yield
    .container-fluid.footer
      = render 'layouts/footer'

app/views/shared/_attachments.html.slim
- if object.attachments.present?
  p Прикркпленные файлы:
  ul
    - object.attachments.each do |a|
      .attachment id="attachment-#{a.id}"
        li
          hr
          - cache [ 'attachment', a ] do
            - if a.persisted?
              .file-link
                = link_to a.file.identifier, a.file.url
          - if can? :destroy, a
            .remove-file
              = link_to '', attachment_path(a), method: :delete, remote: true,
                class: 'glyphicon glyphicon-trash'
          hr

app/views/shared/_vote.html.slim
- obj_name = object.class.name.downcase.pluralize
div id="voting-for-#{obj_name}-#{object.id}" class="voting" data-obj="#{obj_name}" data-id="#{object.id}"
  .col-xs-6.col-sm-4.col-md-4
    .col-xs-1
      - if can? :vote, object
        = link_to '', down, method: :patch, remote: true, class: "button button-down glyphicon glyphicon-chevron-down"

    .col-xs-1
      - cache [ 'rating', object ] do
        div class="#{obj_name}-rating"
          p title="Рейтинг" = object.rating

    .col-xs-1
      - if can? :vote, object
        = link_to '', up, method: :patch, remote: true, class: "button button-up glyphicon glyphicon-chevron-up"

  .col-xs-6.col-sm-4.col-md-4.button-reset
    - if can? :vote_reset, object
      = link_to 'Переголосовать', reset, method: :delete, remote: true, title: "Отменить свой голос"